version: '3.9'

services:
  djangoproject:
    container_name: djangoproject
    build:
      context: .
    ports:
      - 8000:8000
    # volumes:
    #   - ./djangoproject:/djangoproject/
    #   - ./data/web/static:/data/web/static/
    #   - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    # depends_on:
    #   - psql
    # psql:
    #   container_name: psql
    #   image: postgres:15-alpine3.18
    #   volumes:
    #     - ./data/postgres/data:/var/lib/postgresql/data/
    #   env_file:
    #     - ./dotenv_files/.env
