# Generated by Django 4.2.1 on 2023-08-17 13:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app_crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="ada",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="avax",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="bnb",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="btc",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="busd",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dai",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="doge",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dot",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="etc",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eth",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="hex",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="leo",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="ltc",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="matic",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="shib",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sol",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="steth",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="trx",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usdc",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usdt",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="wbtc",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="wtrx",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="xrp",
            managers=[
                ("crypto_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
