# Generated by Django 4.2.1 on 2023-08-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_crypto", "0003_alter_ada_date_alter_avax_date_alter_bnb_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ada",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="avax",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="bnb",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="btc",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="busd",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="dai",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="doge",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="dot",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="etc",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="eth",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="hex",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="leo",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="ltc",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="matic",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="shib",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="sol",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="steth",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="trx",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="usdc",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="usdt",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="wbtc",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="wtrx",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
        migrations.AlterField(
            model_name="xrp",
            name="date",
            field=models.DateField(blank=True, db_column="Date", null=True),
        ),
    ]
