# Generated by Django 4.2.1 on 2023-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bnb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Btc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Busd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Eth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ltc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shib",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Steth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usdc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usdt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wbtc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wtrx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Xrp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("open", models.FloatField(blank=True, db_column="Open", null=True)),
                ("high", models.FloatField(blank=True, db_column="High", null=True)),
                ("low", models.FloatField(blank=True, db_column="Low", null=True)),
                ("close", models.FloatField(blank=True, db_column="Close", null=True)),
                (
                    "adj_close",
                    models.FloatField(blank=True, db_column="Adj Close", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="Volume", null=True),
                ),
            ],
        ),
    ]
