# Generated by Django 4.2.1 on 2023-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="btc",
            name="date",
            field=models.TimeField(blank=True, db_column="Date", null=True),
        ),
    ]
