# Generated by Django 4.2.1 on 2023-06-14 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_crypto", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Uni1",
        ),
    ]
