# Generated by Django 4.2.1 on 2023-08-12 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_crypto",
            "0002_ada_avax_bnb_btc_busd_dai_doge_dot_etc_eth_hex_leo_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ada",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="avax",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="bnb",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="btc",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="busd",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="dai",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="doge",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="dot",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="etc",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="eth",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="hex",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="leo",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="ltc",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="matic",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="shib",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="sol",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="steth",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="trx",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="usdc",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="usdt",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wbtc",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wtrx",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="xrp",
            options={"managed": False},
        ),
    ]
